// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

// WeaveFFI WASM bindings (auto-generated)
//
// Complex type conventions at the WASM boundary:
//
//   Structs   -> i64 opaque handle (pointer into linear memory)
//   Enums     -> i32 discriminant value
//   Optionals -> 0/null for absent; for numerics a separate _is_present i32 flag
//   Lists     -> (i32 pointer, i32 length) pair into linear memory

function _allocError(wasm) {
  return wasm.weaveffi_alloc(8);
}

function _checkError(wasm, errPtr) {
  const buffer = wasm.memory.buffer;
  const code = new Int32Array(buffer, errPtr, 1)[0];
  if (code !== 0) {
    const msgPtr = new Uint32Array(buffer, errPtr + 4, 1)[0];
    const bytes = new Uint8Array(buffer, msgPtr);
    let end = 0;
    while (bytes[end] !== 0) end++;
    const msg = new TextDecoder().decode(new Uint8Array(buffer, msgPtr, end));
    wasm.weaveffi_error_clear(errPtr);
    throw new Error(`WeaveFFI error ${code}: ${msg}`);
  }
}

export const ImageFormat = Object.freeze({
  Png: 0,
  Jpeg: 1,
  Webp: 2,
  Gif: 3,
});

export const OpKind = Object.freeze({
  Resize: 0,
  Crop: 1,
  Rotate: 2,
  Blur: 3,
  Grayscale: 4,
});

class Operation {
  constructor(wasm, handle) {
    this._wasm = wasm;
    this._handle = handle;
  }
  get kind() {
    return this._wasm.weaveffi_image_Operation_get_kind(this._handle);
  }
  get width() {
    return this._wasm.weaveffi_image_Operation_get_width(this._handle);
  }
  get height() {
    return this._wasm.weaveffi_image_Operation_get_height(this._handle);
  }
  get x() {
    return this._wasm.weaveffi_image_Operation_get_x(this._handle);
  }
  get y() {
    return this._wasm.weaveffi_image_Operation_get_y(this._handle);
  }
  get degrees() {
    return this._wasm.weaveffi_image_Operation_get_degrees(this._handle);
  }
  get sigma() {
    return this._wasm.weaveffi_image_Operation_get_sigma(this._handle);
  }
}

class ImageInfo {
  constructor(wasm, handle) {
    this._wasm = wasm;
    this._handle = handle;
  }
  get width() {
    return this._wasm.weaveffi_image_ImageInfo_get_width(this._handle);
  }
  get height() {
    return this._wasm.weaveffi_image_ImageInfo_get_height(this._handle);
  }
  get format() {
    return this._wasm.weaveffi_image_ImageInfo_get_format(this._handle);
  }
}

/**
 * Load a WeaveFFI WASM module from the given URL.
 *
 * @param {string} url - URL to the `.wasm` file.
 * @returns {Promise<Object>} The API bindings.
 *
 * Exported functions follow the C ABI naming convention:
 *   weaveffi_{module}_{function}(params...) -> result
 *
 * @example
 * const api = await loadWeaveffiWasm('lib.wasm');
 *
 * // Primitive: (i32, i32) -> i32
 * const sum = api.math.add(1, 2);
 *
 * // Struct handle: () -> i64 (opaque pointer)
 * const handle = api.contacts.create();
 *
 * // Enum: (i32 discriminant) -> void
 * api.ui.set_color(0); // 0 = first variant
 *
 * // Optional: (i32 is_present, i32 value) -> void
 * api.config.set_timeout(1, 5000); // present
 * api.config.set_timeout(0, 0);    // absent
 *
 * // List: (i32 pointer, i32 length) -> void
 * api.data.process(ptr, len);
 */
export async function loadWeaveffiWasm(url) {
  const response = await fetch(url);
  const bytes = await response.arrayBuffer();
  const { instance } = await WebAssembly.instantiate(bytes, {});
  const wasm = instance.exports;

  return {
    _raw: wasm,
    image: {
      resize(width, height) {
        const _err = _allocError(wasm);
        const _result = wasm.weaveffi_image_resize(width, height, _err);
        _checkError(wasm, _err);
        return new Operation(wasm, _result);
      },
      crop(x, y, width, height) {
        const _err = _allocError(wasm);
        const _result = wasm.weaveffi_image_crop(x, y, width, height, _err);
        _checkError(wasm, _err);
        return new Operation(wasm, _result);
      },
      rotate(degrees) {
        const _err = _allocError(wasm);
        const _result = wasm.weaveffi_image_rotate(degrees, _err);
        _checkError(wasm, _err);
        return new Operation(wasm, _result);
      },
      blur(sigma) {
        const _err = _allocError(wasm);
        const _result = wasm.weaveffi_image_blur(sigma, _err);
        _checkError(wasm, _err);
        return new Operation(wasm, _result);
      },
      grayscale() {
        const _err = _allocError(wasm);
        const _result = wasm.weaveffi_image_grayscale(_err);
        _checkError(wasm, _err);
        return new Operation(wasm, _result);
      },
      process(input, ops, out_format) {
        const _err = _allocError(wasm);
        const _result = wasm.weaveffi_image_process(input, ops, out_format, _err);
        _checkError(wasm, _err);
        return _result;
      },
      probe(input) {
        const _err = _allocError(wasm);
        const _result = wasm.weaveffi_image_probe(input, _err);
        _checkError(wasm, _err);
        return new ImageInfo(wasm, _result);
      },
    },
  };
}

// END weaveffi_wasm.js
