// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

// Generated TypeScript declarations for WeaveFFI WASM bindings

/**
 * Single image operation. Build with the resize/crop/rotate/blur/grayscale
 * factory functions; pass a list to process(). Fields used per kind:
 *   Resize    : width, height
 *   Crop      : x, y, width, height
 *   Rotate    : degrees (clockwise, in degrees)
 *   Blur      : sigma   (Gaussian sigma, in pixels)
 *   Grayscale : (none)
 * Unused fields are null.
 */
export interface Operation {
  readonly kind: OpKind;
  readonly width: number | null;
  readonly height: number | null;
  readonly x: number | null;
  readonly y: number | null;
  readonly degrees: number | null;
  readonly sigma: number | null;
}

/** Decoded image header information. */
export interface ImageInfo {
  readonly width: number;
  readonly height: number;
  readonly format: ImageFormat;
}

/** Encoded image container. */
export declare const ImageFormat: Readonly<{
  Png: 0;
  Jpeg: 1;
  Webp: 2;
  Gif: 3;
}>;

/** Operation discriminator. See Operation for which fields each kind requires. */
export declare const OpKind: Readonly<{
  Resize: 0;
  Crop: 1;
  Rotate: 2;
  Blur: 3;
  Grayscale: 4;
}>;

export interface WeaveffiWasmModule {
  _raw: WebAssembly.Exports;
  image: {
    /**
     * Build a Resize operation.
     * @throws {Error} if the native call fails
     */
    resize(width: number, height: number): Operation;
    /**
     * Build a Crop operation (x,y is the top-left corner).
     * @throws {Error} if the native call fails
     */
    crop(x: number, y: number, width: number, height: number): Operation;
    /**
     * Build a Rotate operation (degrees clockwise).
     * @throws {Error} if the native call fails
     */
    rotate(degrees: number): Operation;
    /**
     * Build a Gaussian Blur operation (sigma in pixels).
     * @throws {Error} if the native call fails
     */
    blur(sigma: number): Operation;
    /**
     * Build a Grayscale operation.
     * @throws {Error} if the native call fails
     */
    grayscale(): Operation;
    /**
     * Apply ops in order, encode in out_format, return bytes.
     * @throws {Error} if the native call fails
     */
    process(input: Buffer, ops: Operation[], out_format: ImageFormat): Buffer;
    /**
     * Decode the header only and return dimensions plus detected format.
     * @throws {Error} if the native call fails
     */
    probe(input: Buffer): ImageInfo;
  };
}

export function loadWeaveffiWasm(url: string): Promise<WeaveffiWasmModule>;

// END weaveffi_wasm.d.ts
