// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

// ignore_for_file: non_constant_identifier_names, camel_case_types

import 'dart:ffi';
import 'dart:io' show Platform;
import 'package:ffi/ffi.dart';

DynamicLibrary _openLibrary() {
  if (Platform.isMacOS) return DynamicLibrary.open('libweaveffi.dylib');
  if (Platform.isLinux) return DynamicLibrary.open('libweaveffi.so');
  if (Platform.isWindows) return DynamicLibrary.open('weaveffi.dll');
  throw UnsupportedError('Unsupported platform: ${Platform.operatingSystem}');
}

final DynamicLibrary _lib = _openLibrary();

final class _WeaveffiError extends Struct {
  @Int32()
  external int code;
  external Pointer<Utf8> message;
}

typedef _NativeWeaveffiErrorClear = Void Function(Pointer<_WeaveffiError>);
typedef _DartWeaveffiErrorClear = void Function(Pointer<_WeaveffiError>);
final _weaveffiErrorClear = _lib.lookupFunction<
    _NativeWeaveffiErrorClear, _DartWeaveffiErrorClear>('weaveffi_error_clear');

class WeaveffiException implements Exception {
  final int code;
  final String message;
  WeaveffiException(this.code, this.message);
  @override
  String toString() => 'WeaveffiException($code): $message';
}

void _checkError(Pointer<_WeaveffiError> err) {
  if (err.ref.code != 0) {
    final msg = err.ref.message.toDartString();
    _weaveffiErrorClear(err);
    throw WeaveffiException(err.ref.code, msg);
  }
}

/// Encoded image container.
enum ImageFormat {
  png(0),
  jpeg(1),
  webp(2),
  gif(3),
  ;
  const ImageFormat(this.value);
  final int value;

  static ImageFormat fromValue(int value) =>
      ImageFormat.values.firstWhere((e) => e.value == value);
}

/// Operation discriminator. See Operation for which fields each kind requires.
enum OpKind {
  resize(0),
  crop(1),
  rotate(2),
  blur(3),
  grayscale(4),
  ;
  const OpKind(this.value);
  final int value;

  static OpKind fromValue(int value) =>
      OpKind.values.firstWhere((e) => e.value == value);
}

typedef _NativeWeaveffiImageOperationDestroy = Void Function(Pointer<Void>);
typedef _DartWeaveffiImageOperationDestroy = void Function(Pointer<Void>);
final _weaveffiImageOperationDestroy = _lib.lookupFunction<
    _NativeWeaveffiImageOperationDestroy, _DartWeaveffiImageOperationDestroy>('weaveffi_image_Operation_destroy');

typedef _NativeWeaveffiImageOperationGetKind = Int32 Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageOperationGetKind = int Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageOperationGetKind = _lib.lookupFunction<
    _NativeWeaveffiImageOperationGetKind, _DartWeaveffiImageOperationGetKind>('weaveffi_image_Operation_get_kind');

typedef _NativeWeaveffiImageOperationGetWidth = Uint32 Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageOperationGetWidth = int Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageOperationGetWidth = _lib.lookupFunction<
    _NativeWeaveffiImageOperationGetWidth, _DartWeaveffiImageOperationGetWidth>('weaveffi_image_Operation_get_width');

typedef _NativeWeaveffiImageOperationGetHeight = Uint32 Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageOperationGetHeight = int Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageOperationGetHeight = _lib.lookupFunction<
    _NativeWeaveffiImageOperationGetHeight, _DartWeaveffiImageOperationGetHeight>('weaveffi_image_Operation_get_height');

typedef _NativeWeaveffiImageOperationGetX = Uint32 Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageOperationGetX = int Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageOperationGetX = _lib.lookupFunction<
    _NativeWeaveffiImageOperationGetX, _DartWeaveffiImageOperationGetX>('weaveffi_image_Operation_get_x');

typedef _NativeWeaveffiImageOperationGetY = Uint32 Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageOperationGetY = int Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageOperationGetY = _lib.lookupFunction<
    _NativeWeaveffiImageOperationGetY, _DartWeaveffiImageOperationGetY>('weaveffi_image_Operation_get_y');

typedef _NativeWeaveffiImageOperationGetDegrees = Double Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageOperationGetDegrees = double Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageOperationGetDegrees = _lib.lookupFunction<
    _NativeWeaveffiImageOperationGetDegrees, _DartWeaveffiImageOperationGetDegrees>('weaveffi_image_Operation_get_degrees');

typedef _NativeWeaveffiImageOperationGetSigma = Double Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageOperationGetSigma = double Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageOperationGetSigma = _lib.lookupFunction<
    _NativeWeaveffiImageOperationGetSigma, _DartWeaveffiImageOperationGetSigma>('weaveffi_image_Operation_get_sigma');

/// Single image operation. Build with the resize/crop/rotate/blur/grayscale
/// factory functions; pass a list to process(). Fields used per kind:
///   Resize    : width, height
///   Crop      : x, y, width, height
///   Rotate    : degrees (clockwise, in degrees)
///   Blur      : sigma   (Gaussian sigma, in pixels)
///   Grayscale : (none)
/// Unused fields are null.
class Operation {
  final Pointer<Void> _handle;
  Operation._(this._handle);

  void dispose() {
    _weaveffiImageOperationDestroy(_handle);
  }

  OpKind get kind {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageOperationGetKind(_handle, err);
      _checkError(err);
      return OpKind.fromValue(result);
    } finally {
      calloc.free(err);
    }
  }

  int? get width {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageOperationGetWidth(_handle, err);
      _checkError(err);
      return result;
    } finally {
      calloc.free(err);
    }
  }

  int? get height {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageOperationGetHeight(_handle, err);
      _checkError(err);
      return result;
    } finally {
      calloc.free(err);
    }
  }

  int? get x {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageOperationGetX(_handle, err);
      _checkError(err);
      return result;
    } finally {
      calloc.free(err);
    }
  }

  int? get y {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageOperationGetY(_handle, err);
      _checkError(err);
      return result;
    } finally {
      calloc.free(err);
    }
  }

  double? get degrees {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageOperationGetDegrees(_handle, err);
      _checkError(err);
      return result;
    } finally {
      calloc.free(err);
    }
  }

  double? get sigma {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageOperationGetSigma(_handle, err);
      _checkError(err);
      return result;
    } finally {
      calloc.free(err);
    }
  }
}

typedef _NativeWeaveffiImageImageInfoDestroy = Void Function(Pointer<Void>);
typedef _DartWeaveffiImageImageInfoDestroy = void Function(Pointer<Void>);
final _weaveffiImageImageInfoDestroy = _lib.lookupFunction<
    _NativeWeaveffiImageImageInfoDestroy, _DartWeaveffiImageImageInfoDestroy>('weaveffi_image_ImageInfo_destroy');

typedef _NativeWeaveffiImageImageInfoGetWidth = Uint32 Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageImageInfoGetWidth = int Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageImageInfoGetWidth = _lib.lookupFunction<
    _NativeWeaveffiImageImageInfoGetWidth, _DartWeaveffiImageImageInfoGetWidth>('weaveffi_image_ImageInfo_get_width');

typedef _NativeWeaveffiImageImageInfoGetHeight = Uint32 Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageImageInfoGetHeight = int Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageImageInfoGetHeight = _lib.lookupFunction<
    _NativeWeaveffiImageImageInfoGetHeight, _DartWeaveffiImageImageInfoGetHeight>('weaveffi_image_ImageInfo_get_height');

typedef _NativeWeaveffiImageImageInfoGetFormat = Int32 Function(Pointer<Void>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageImageInfoGetFormat = int Function(Pointer<Void>, Pointer<_WeaveffiError>);
final _weaveffiImageImageInfoGetFormat = _lib.lookupFunction<
    _NativeWeaveffiImageImageInfoGetFormat, _DartWeaveffiImageImageInfoGetFormat>('weaveffi_image_ImageInfo_get_format');

/// Decoded image header information.
class ImageInfo {
  final Pointer<Void> _handle;
  ImageInfo._(this._handle);

  void dispose() {
    _weaveffiImageImageInfoDestroy(_handle);
  }

  int get width {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageImageInfoGetWidth(_handle, err);
      _checkError(err);
      return result;
    } finally {
      calloc.free(err);
    }
  }

  int get height {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageImageInfoGetHeight(_handle, err);
      _checkError(err);
      return result;
    } finally {
      calloc.free(err);
    }
  }

  ImageFormat get format {
    final err = calloc<_WeaveffiError>();
    try {
      final result = _weaveffiImageImageInfoGetFormat(_handle, err);
      _checkError(err);
      return ImageFormat.fromValue(result);
    } finally {
      calloc.free(err);
    }
  }
}

typedef _NativeWeaveffiImageResize = Pointer<Void> Function(Uint32, Uint32, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageResize = Pointer<Void> Function(int, int, Pointer<_WeaveffiError>);
final _weaveffiImageResize = _lib.lookupFunction<
    _NativeWeaveffiImageResize, _DartWeaveffiImageResize>('weaveffi_image_resize');

/// Build a Resize operation.
Operation resize(int width, int height) {
  final err = calloc<_WeaveffiError>();
  try {
    final result = _weaveffiImageResize(width, height, err);
    _checkError(err);
    return Operation._(result);
  } finally {
    calloc.free(err);
  }
}

typedef _NativeWeaveffiImageCrop = Pointer<Void> Function(Uint32, Uint32, Uint32, Uint32, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageCrop = Pointer<Void> Function(int, int, int, int, Pointer<_WeaveffiError>);
final _weaveffiImageCrop = _lib.lookupFunction<
    _NativeWeaveffiImageCrop, _DartWeaveffiImageCrop>('weaveffi_image_crop');

/// Build a Crop operation (x,y is the top-left corner).
Operation crop(int x, int y, int width, int height) {
  final err = calloc<_WeaveffiError>();
  try {
    final result = _weaveffiImageCrop(x, y, width, height, err);
    _checkError(err);
    return Operation._(result);
  } finally {
    calloc.free(err);
  }
}

typedef _NativeWeaveffiImageRotate = Pointer<Void> Function(Double, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageRotate = Pointer<Void> Function(double, Pointer<_WeaveffiError>);
final _weaveffiImageRotate = _lib.lookupFunction<
    _NativeWeaveffiImageRotate, _DartWeaveffiImageRotate>('weaveffi_image_rotate');

/// Build a Rotate operation (degrees clockwise).
Operation rotate(double degrees) {
  final err = calloc<_WeaveffiError>();
  try {
    final result = _weaveffiImageRotate(degrees, err);
    _checkError(err);
    return Operation._(result);
  } finally {
    calloc.free(err);
  }
}

typedef _NativeWeaveffiImageBlur = Pointer<Void> Function(Double, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageBlur = Pointer<Void> Function(double, Pointer<_WeaveffiError>);
final _weaveffiImageBlur = _lib.lookupFunction<
    _NativeWeaveffiImageBlur, _DartWeaveffiImageBlur>('weaveffi_image_blur');

/// Build a Gaussian Blur operation (sigma in pixels).
Operation blur(double sigma) {
  final err = calloc<_WeaveffiError>();
  try {
    final result = _weaveffiImageBlur(sigma, err);
    _checkError(err);
    return Operation._(result);
  } finally {
    calloc.free(err);
  }
}

typedef _NativeWeaveffiImageGrayscale = Pointer<Void> Function(Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageGrayscale = Pointer<Void> Function(Pointer<_WeaveffiError>);
final _weaveffiImageGrayscale = _lib.lookupFunction<
    _NativeWeaveffiImageGrayscale, _DartWeaveffiImageGrayscale>('weaveffi_image_grayscale');

/// Build a Grayscale operation.
Operation grayscale() {
  final err = calloc<_WeaveffiError>();
  try {
    final result = _weaveffiImageGrayscale(err);
    _checkError(err);
    return Operation._(result);
  } finally {
    calloc.free(err);
  }
}

typedef _NativeWeaveffiImageProcess = Pointer<Uint8> Function(Pointer<Uint8>, Pointer<Void>, Int32, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageProcess = Pointer<Uint8> Function(Pointer<Uint8>, Pointer<Void>, int, Pointer<_WeaveffiError>);
final _weaveffiImageProcess = _lib.lookupFunction<
    _NativeWeaveffiImageProcess, _DartWeaveffiImageProcess>('weaveffi_image_process');

/// Apply ops in order, encode in out_format, return bytes.
List<int> process(List<int> input, List<Operation> ops, ImageFormat outFormat) {
  final err = calloc<_WeaveffiError>();
  try {
    final result = _weaveffiImageProcess(input, ops, outFormat.value, err);
    _checkError(err);
    return result;
  } finally {
    calloc.free(err);
  }
}

typedef _NativeWeaveffiImageProbe = Pointer<Void> Function(Pointer<Uint8>, Pointer<_WeaveffiError>);
typedef _DartWeaveffiImageProbe = Pointer<Void> Function(Pointer<Uint8>, Pointer<_WeaveffiError>);
final _weaveffiImageProbe = _lib.lookupFunction<
    _NativeWeaveffiImageProbe, _DartWeaveffiImageProbe>('weaveffi_image_probe');

/// Decode the header only and return dimensions plus detected format.
ImageInfo probe(List<int> input) {
  final err = calloc<_WeaveffiError>();
  try {
    final result = _weaveffiImageProbe(input, err);
    _checkError(err);
    return ImageInfo._(result);
  } finally {
    calloc.free(err);
  }
}

// END weaveffi.dart
