// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace WeaveImage
{
    public class WeaveffiException : Exception
    {
        public int Code { get; }

        public WeaveffiException(int code, string message) : base(message)
        {
            Code = code;
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct WeaveffiError
    {
        public int Code;
        public IntPtr Message;

        internal static void Check(WeaveffiError err)
        {
            if (err.Code != 0)
            {
                var msg = Marshal.PtrToStringUTF8(err.Message) ?? "";
                throw new WeaveffiException(err.Code, msg);
            }
        }
    }

    internal static class WeaveFFIHelpers
    {
        internal static IntPtr StringToPtr(string? s)
        {
            return s == null ? IntPtr.Zero : Marshal.StringToCoTaskMemUTF8(s);
        }

        internal static string? PtrToString(IntPtr ptr)
        {
            return ptr == IntPtr.Zero ? null : Marshal.PtrToStringUTF8(ptr);
        }

        internal static void FreePtr(IntPtr ptr)
        {
            Marshal.FreeCoTaskMem(ptr);
        }
    }

    /// <summary>Encoded image container.</summary>
    public enum ImageFormat
    {
        Png = 0,
        Jpeg = 1,
        Webp = 2,
        Gif = 3,
    }

    /// <summary>Operation discriminator. See Operation for which fields each kind requires.</summary>
    public enum OpKind
    {
        Resize = 0,
        Crop = 1,
        Rotate = 2,
        Blur = 3,
        Grayscale = 4,
    }

    /// <summary>
    /// Single image operation. Build with the resize/crop/rotate/blur/grayscale
    /// factory functions; pass a list to process(). Fields used per kind:
    ///   Resize    : width, height
    ///   Crop      : x, y, width, height
    ///   Rotate    : degrees (clockwise, in degrees)
    ///   Blur      : sigma   (Gaussian sigma, in pixels)
    ///   Grayscale : (none)
    /// Unused fields are null.
    /// </summary>
    public class Operation : IDisposable
    {
        private IntPtr _handle;
        private bool _disposed;

        internal Operation(IntPtr handle)
        {
            _handle = handle;
        }

        internal IntPtr Handle => _handle;

        public OpKind Kind
        {
            get
            {
                return (OpKind)NativeMethods.weaveffi_image_Operation_get_kind(_handle);
            }
        }

        public uint? Width
        {
            get
            {
                var ptr = NativeMethods.weaveffi_image_Operation_get_width(_handle);
                if (ptr == IntPtr.Zero) return null;
                return (uint)Marshal.ReadInt32(ptr);
            }
        }

        public uint? Height
        {
            get
            {
                var ptr = NativeMethods.weaveffi_image_Operation_get_height(_handle);
                if (ptr == IntPtr.Zero) return null;
                return (uint)Marshal.ReadInt32(ptr);
            }
        }

        public uint? X
        {
            get
            {
                var ptr = NativeMethods.weaveffi_image_Operation_get_x(_handle);
                if (ptr == IntPtr.Zero) return null;
                return (uint)Marshal.ReadInt32(ptr);
            }
        }

        public uint? Y
        {
            get
            {
                var ptr = NativeMethods.weaveffi_image_Operation_get_y(_handle);
                if (ptr == IntPtr.Zero) return null;
                return (uint)Marshal.ReadInt32(ptr);
            }
        }

        public double? Degrees
        {
            get
            {
                var ptr = NativeMethods.weaveffi_image_Operation_get_degrees(_handle);
                if (ptr == IntPtr.Zero) return null;
                return BitConverter.Int64BitsToDouble(Marshal.ReadInt64(ptr));
            }
        }

        public double? Sigma
        {
            get
            {
                var ptr = NativeMethods.weaveffi_image_Operation_get_sigma(_handle);
                if (ptr == IntPtr.Zero) return null;
                return BitConverter.Int64BitsToDouble(Marshal.ReadInt64(ptr));
            }
        }

        public void Dispose()
        {
            if (!_disposed)
            {
                NativeMethods.weaveffi_image_Operation_destroy(_handle);
                _disposed = true;
            }
            GC.SuppressFinalize(this);
        }

        ~Operation()
        {
            Dispose();
        }
    }

    /// <summary>Decoded image header information.</summary>
    public class ImageInfo : IDisposable
    {
        private IntPtr _handle;
        private bool _disposed;

        internal ImageInfo(IntPtr handle)
        {
            _handle = handle;
        }

        internal IntPtr Handle => _handle;

        public uint Width
        {
            get
            {
                return NativeMethods.weaveffi_image_ImageInfo_get_width(_handle);
            }
        }

        public uint Height
        {
            get
            {
                return NativeMethods.weaveffi_image_ImageInfo_get_height(_handle);
            }
        }

        public ImageFormat Format
        {
            get
            {
                return (ImageFormat)NativeMethods.weaveffi_image_ImageInfo_get_format(_handle);
            }
        }

        public void Dispose()
        {
            if (!_disposed)
            {
                NativeMethods.weaveffi_image_ImageInfo_destroy(_handle);
                _disposed = true;
            }
            GC.SuppressFinalize(this);
        }

        ~ImageInfo()
        {
            Dispose();
        }
    }

    internal static class NativeMethods
    {
        private const string LibName = "weaveffi";

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        internal static extern void weaveffi_free_string(IntPtr ptr);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        internal static extern void weaveffi_free_bytes(IntPtr ptr, UIntPtr len);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_create", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_Operation_create(int kind, IntPtr width, IntPtr height, IntPtr x, IntPtr y, IntPtr degrees, IntPtr sigma, ref WeaveffiError err);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_destroy", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void weaveffi_image_Operation_destroy(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_get_kind", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int weaveffi_image_Operation_get_kind(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_get_width", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_Operation_get_width(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_get_height", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_Operation_get_height(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_get_x", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_Operation_get_x(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_get_y", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_Operation_get_y(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_get_degrees", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_Operation_get_degrees(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_Operation_get_sigma", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_Operation_get_sigma(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_ImageInfo_create", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_ImageInfo_create(uint width, uint height, int format, ref WeaveffiError err);

        [DllImport(LibName, EntryPoint = "weaveffi_image_ImageInfo_destroy", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void weaveffi_image_ImageInfo_destroy(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_ImageInfo_get_width", CallingConvention = CallingConvention.Cdecl)]
        internal static extern uint weaveffi_image_ImageInfo_get_width(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_ImageInfo_get_height", CallingConvention = CallingConvention.Cdecl)]
        internal static extern uint weaveffi_image_ImageInfo_get_height(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_ImageInfo_get_format", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int weaveffi_image_ImageInfo_get_format(IntPtr ptr);

        [DllImport(LibName, EntryPoint = "weaveffi_image_resize", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_resize(uint width, uint height, ref WeaveffiError err);

        [DllImport(LibName, EntryPoint = "weaveffi_image_crop", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_crop(uint x, uint y, uint width, uint height, ref WeaveffiError err);

        [DllImport(LibName, EntryPoint = "weaveffi_image_rotate", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_rotate(double degrees, ref WeaveffiError err);

        [DllImport(LibName, EntryPoint = "weaveffi_image_blur", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_blur(double sigma, ref WeaveffiError err);

        [DllImport(LibName, EntryPoint = "weaveffi_image_grayscale", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_grayscale(ref WeaveffiError err);

        [DllImport(LibName, EntryPoint = "weaveffi_image_process", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_process(IntPtr input_ptr, UIntPtr input_len, IntPtr ops, UIntPtr ops_len, int out_format, out UIntPtr out_len, ref WeaveffiError err);

        [DllImport(LibName, EntryPoint = "weaveffi_image_probe", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr weaveffi_image_probe(IntPtr input_ptr, UIntPtr input_len, ref WeaveffiError err);

    }

    public static class Image
    {
        /// <summary>Build a Resize operation.</summary>
        public static Operation Resize(uint width, uint height)
        {
            var err = new WeaveffiError();
            var result = NativeMethods.weaveffi_image_resize(width, height, ref err);
            WeaveffiError.Check(err);
            return new Operation(result);
        }

        /// <summary>Build a Crop operation (x,y is the top-left corner).</summary>
        public static Operation Crop(uint x, uint y, uint width, uint height)
        {
            var err = new WeaveffiError();
            var result = NativeMethods.weaveffi_image_crop(x, y, width, height, ref err);
            WeaveffiError.Check(err);
            return new Operation(result);
        }

        /// <summary>Build a Rotate operation (degrees clockwise).</summary>
        public static Operation Rotate(double degrees)
        {
            var err = new WeaveffiError();
            var result = NativeMethods.weaveffi_image_rotate(degrees, ref err);
            WeaveffiError.Check(err);
            return new Operation(result);
        }

        /// <summary>Build a Gaussian Blur operation (sigma in pixels).</summary>
        public static Operation Blur(double sigma)
        {
            var err = new WeaveffiError();
            var result = NativeMethods.weaveffi_image_blur(sigma, ref err);
            WeaveffiError.Check(err);
            return new Operation(result);
        }

        /// <summary>Build a Grayscale operation.</summary>
        public static Operation Grayscale()
        {
            var err = new WeaveffiError();
            var result = NativeMethods.weaveffi_image_grayscale(ref err);
            WeaveffiError.Check(err);
            return new Operation(result);
        }

        /// <summary>Apply ops in order, encode in out_format, return bytes.</summary>
        public static byte[] Process(byte[] input, Operation[] ops, ImageFormat out_format)
        {
            var err = new WeaveffiError();
            var inputPin = GCHandle.Alloc(input, GCHandleType.Pinned);
            try
            {
                var result = NativeMethods.weaveffi_image_process(inputPin.AddrOfPinnedObject(), (UIntPtr)input.Length, ops, (int)out_format, out var outLen, ref err);
                WeaveffiError.Check(err);
                if (result == IntPtr.Zero) return Array.Empty<byte>();
                var arr = new byte[(int)outLen];
                Marshal.Copy(result, arr, 0, (int)outLen);
                NativeMethods.weaveffi_free_bytes(result, outLen);
                return arr;
            }
            finally
            {
                inputPin.Free();
            }
        }

        /// <summary>Decode the header only and return dimensions plus detected format.</summary>
        public static ImageInfo Probe(byte[] input)
        {
            var err = new WeaveffiError();
            var inputPin = GCHandle.Alloc(input, GCHandleType.Pinned);
            try
            {
                var result = NativeMethods.weaveffi_image_probe(inputPin.AddrOfPinnedObject(), (UIntPtr)input.Length, ref err);
                WeaveffiError.Check(err);
                return new ImageInfo(result);
            }
            finally
            {
                inputPin.Free();
            }
        }

    }

}

// END WeaveImage.cs
