// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

package weaveffi

/*
#cgo LDFLAGS: -lweaveffi
#include "weaveffi.h"
#include <stdlib.h>
*/
import "C"

import (
	"fmt"
	"unsafe"
)

// ImageFormat: Encoded image container.
type ImageFormat int32

const (
	ImageFormatPng ImageFormat = 0
	ImageFormatJpeg ImageFormat = 1
	ImageFormatWebp ImageFormat = 2
	ImageFormatGif ImageFormat = 3
)

// OpKind: Operation discriminator. See Operation for which fields each kind requires.
type OpKind int32

const (
	OpKindResize OpKind = 0
	OpKindCrop OpKind = 1
	OpKindRotate OpKind = 2
	OpKindBlur OpKind = 3
	OpKindGrayscale OpKind = 4
)

// Operation: Single image operation. Build with the resize/crop/rotate/blur/grayscale
// factory functions; pass a list to process(). Fields used per kind:
//   Resize    : width, height
//   Crop      : x, y, width, height
//   Rotate    : degrees (clockwise, in degrees)
//   Blur      : sigma   (Gaussian sigma, in pixels)
//   Grayscale : (none)
// Unused fields are null.
type Operation struct {
	ptr *C.weaveffi_image_Operation
}

func (s *Operation) Kind() OpKind {
	return OpKind(C.weaveffi_image_Operation_get_kind(s.ptr))
}

func (s *Operation) Width() *uint32 {
	cVal := C.weaveffi_image_Operation_get_width(s.ptr)
	if cVal == nil {
		return nil
	}
	v := uint32(*cVal)
	return &v
}

func (s *Operation) Height() *uint32 {
	cVal := C.weaveffi_image_Operation_get_height(s.ptr)
	if cVal == nil {
		return nil
	}
	v := uint32(*cVal)
	return &v
}

func (s *Operation) X() *uint32 {
	cVal := C.weaveffi_image_Operation_get_x(s.ptr)
	if cVal == nil {
		return nil
	}
	v := uint32(*cVal)
	return &v
}

func (s *Operation) Y() *uint32 {
	cVal := C.weaveffi_image_Operation_get_y(s.ptr)
	if cVal == nil {
		return nil
	}
	v := uint32(*cVal)
	return &v
}

func (s *Operation) Degrees() *float64 {
	cVal := C.weaveffi_image_Operation_get_degrees(s.ptr)
	if cVal == nil {
		return nil
	}
	v := float64(*cVal)
	return &v
}

func (s *Operation) Sigma() *float64 {
	cVal := C.weaveffi_image_Operation_get_sigma(s.ptr)
	if cVal == nil {
		return nil
	}
	v := float64(*cVal)
	return &v
}

func (s *Operation) Close() {
	if s.ptr != nil {
		C.weaveffi_image_Operation_destroy(s.ptr)
		s.ptr = nil
	}
}

// ImageInfo: Decoded image header information.
type ImageInfo struct {
	ptr *C.weaveffi_image_ImageInfo
}

func (s *ImageInfo) Width() uint32 {
	return uint32(C.weaveffi_image_ImageInfo_get_width(s.ptr))
}

func (s *ImageInfo) Height() uint32 {
	return uint32(C.weaveffi_image_ImageInfo_get_height(s.ptr))
}

func (s *ImageInfo) Format() ImageFormat {
	return ImageFormat(C.weaveffi_image_ImageInfo_get_format(s.ptr))
}

func (s *ImageInfo) Close() {
	if s.ptr != nil {
		C.weaveffi_image_ImageInfo_destroy(s.ptr)
		s.ptr = nil
	}
}

// ImageResize: Build a Resize operation.
func ImageResize(width uint32, height uint32) (*Operation, error) {
	var cErr C.weaveffi_error
	result := C.weaveffi_image_resize(C.uint32_t(width), C.uint32_t(height), &cErr)
	if cErr.code != 0 {
		goErr := fmt.Errorf("weaveffi: %s (code %d)", C.GoString(cErr.message), int(cErr.code))
		C.weaveffi_error_clear(&cErr)
		return nil, goErr
	}
	return &Operation{ptr: result}, nil
}

// ImageCrop: Build a Crop operation (x,y is the top-left corner).
func ImageCrop(x uint32, y uint32, width uint32, height uint32) (*Operation, error) {
	var cErr C.weaveffi_error
	result := C.weaveffi_image_crop(C.uint32_t(x), C.uint32_t(y), C.uint32_t(width), C.uint32_t(height), &cErr)
	if cErr.code != 0 {
		goErr := fmt.Errorf("weaveffi: %s (code %d)", C.GoString(cErr.message), int(cErr.code))
		C.weaveffi_error_clear(&cErr)
		return nil, goErr
	}
	return &Operation{ptr: result}, nil
}

// ImageRotate: Build a Rotate operation (degrees clockwise).
func ImageRotate(degrees float64) (*Operation, error) {
	var cErr C.weaveffi_error
	result := C.weaveffi_image_rotate(C.double(degrees), &cErr)
	if cErr.code != 0 {
		goErr := fmt.Errorf("weaveffi: %s (code %d)", C.GoString(cErr.message), int(cErr.code))
		C.weaveffi_error_clear(&cErr)
		return nil, goErr
	}
	return &Operation{ptr: result}, nil
}

// ImageBlur: Build a Gaussian Blur operation (sigma in pixels).
func ImageBlur(sigma float64) (*Operation, error) {
	var cErr C.weaveffi_error
	result := C.weaveffi_image_blur(C.double(sigma), &cErr)
	if cErr.code != 0 {
		goErr := fmt.Errorf("weaveffi: %s (code %d)", C.GoString(cErr.message), int(cErr.code))
		C.weaveffi_error_clear(&cErr)
		return nil, goErr
	}
	return &Operation{ptr: result}, nil
}

// ImageGrayscale: Build a Grayscale operation.
func ImageGrayscale() (*Operation, error) {
	var cErr C.weaveffi_error
	result := C.weaveffi_image_grayscale(&cErr)
	if cErr.code != 0 {
		goErr := fmt.Errorf("weaveffi: %s (code %d)", C.GoString(cErr.message), int(cErr.code))
		C.weaveffi_error_clear(&cErr)
		return nil, goErr
	}
	return &Operation{ptr: result}, nil
}

// ImageProcess: Apply ops in order, encode in out_format, return bytes.
func ImageProcess(input []byte, ops []*Operation, outFormat ImageFormat) ([]byte, error) {
	var cInputPtr *C.uint8_t
	cInputLen := C.size_t(len(input))
	if len(input) > 0 {
		cInputPtr = (*C.uint8_t)(unsafe.Pointer(&input[0]))
	}
	cOpsLen := C.size_t(len(ops))
	cOpsArr := make([]*C.weaveffi_image_Operation, len(ops))
	for i, item := range ops {
		cOpsArr[i] = item.ptr
	}
	var cOpsPtr **C.weaveffi_image_Operation
	if len(cOpsArr) > 0 {
		cOpsPtr = (**C.weaveffi_image_Operation)(unsafe.Pointer(&cOpsArr[0]))
	}
	var cOutLen C.size_t
	var cErr C.weaveffi_error
	result := C.weaveffi_image_process(cInputPtr, cInputLen, cOpsPtr, cOpsLen, C.weaveffi_image_ImageFormat(outFormat), &cOutLen, &cErr)
	if cErr.code != 0 {
		goErr := fmt.Errorf("weaveffi: %s (code %d)", C.GoString(cErr.message), int(cErr.code))
		C.weaveffi_error_clear(&cErr)
		return nil, goErr
	}
	if result == nil {
		return nil, nil
	}
	goResult := C.GoBytes(unsafe.Pointer(result), C.int(cOutLen))
	C.weaveffi_free_bytes(result, cOutLen)
	return goResult, nil
}

// ImageProbe: Decode the header only and return dimensions plus detected format.
func ImageProbe(input []byte) (*ImageInfo, error) {
	var cInputPtr *C.uint8_t
	cInputLen := C.size_t(len(input))
	if len(input) > 0 {
		cInputPtr = (*C.uint8_t)(unsafe.Pointer(&input[0]))
	}
	var cErr C.weaveffi_error
	result := C.weaveffi_image_probe(cInputPtr, cInputLen, &cErr)
	if cErr.code != 0 {
		goErr := fmt.Errorf("weaveffi: %s (code %d)", C.GoString(cErr.message), int(cErr.code))
		C.weaveffi_error_clear(&cErr)
		return nil, goErr
	}
	return &ImageInfo{ptr: result}, nil
}


// END weaveffi.go
