# Generated by WeaveFFI 0.4.0 from image.yml
# DO NOT EDIT — your changes will be overwritten.
# To regenerate: weaveffi generate image.yml -o <out>

{
  "targets": [
    {
      "target_name": "weaveffi",
      "sources": ["weaveffi_addon.c"],
      "include_dirs": ["../c"],
      "libraries": ["-lweaveffi"]
    }
  ]
}

# END binding.gyp
