// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

// Generated types for WeaveFFI functions
/**
 * Single image operation. Build with the resize/crop/rotate/blur/grayscale
 * factory functions; pass a list to process(). Fields used per kind:
 *   Resize    : width, height
 *   Crop      : x, y, width, height
 *   Rotate    : degrees (clockwise, in degrees)
 *   Blur      : sigma   (Gaussian sigma, in pixels)
 *   Grayscale : (none)
 * Unused fields are null.
 */
export interface Operation {
  kind: OpKind;
  width: number | null;
  height: number | null;
  x: number | null;
  y: number | null;
  degrees: number | null;
  sigma: number | null;
}
/** Decoded image header information. */
export interface ImageInfo {
  width: number;
  height: number;
  format: ImageFormat;
}
/** Encoded image container. */
export enum ImageFormat {
  Png = 0,
  Jpeg = 1,
  Webp = 2,
  Gif = 3,
}
/** Operation discriminator. See Operation for which fields each kind requires. */
export enum OpKind {
  Resize = 0,
  Crop = 1,
  Rotate = 2,
  Blur = 3,
  Grayscale = 4,
}
// module image
/**
 * Build a Resize operation.
 * Maps to C function: weaveffi_image_resize
 */
export function resize(width: number, height: number): Operation
/**
 * Build a Crop operation (x,y is the top-left corner).
 * Maps to C function: weaveffi_image_crop
 */
export function crop(x: number, y: number, width: number, height: number): Operation
/**
 * Build a Rotate operation (degrees clockwise).
 * Maps to C function: weaveffi_image_rotate
 */
export function rotate(degrees: number): Operation
/**
 * Build a Gaussian Blur operation (sigma in pixels).
 * Maps to C function: weaveffi_image_blur
 */
export function blur(sigma: number): Operation
/**
 * Build a Grayscale operation.
 * Maps to C function: weaveffi_image_grayscale
 */
export function grayscale(): Operation
/**
 * Apply ops in order, encode in out_format, return bytes.
 * Maps to C function: weaveffi_image_process
 */
export function process(input: Buffer, ops: Operation[], out_format: ImageFormat): Buffer
/**
 * Decode the header only and return dimensions plus detected format.
 * Maps to C function: weaveffi_image_probe
 */
export function probe(input: Buffer): ImageInfo

// END types.d.ts
