// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

#include <node_api.h>
#include "weaveffi.h"
#include <stdlib.h>
#include <string.h>

static napi_value Napi_weaveffi_image_resize(napi_env env, napi_callback_info info) {
  size_t argc = 2;
  napi_value args[2];
  napi_get_cb_info(env, info, &argc, args, NULL, NULL);
  uint32_t width;
  napi_get_value_uint32(env, args[0], &width);
  uint32_t height;
  napi_get_value_uint32(env, args[1], &height);
  weaveffi_error err = {0};
  weaveffi_image_Operation* result = weaveffi_image_resize(width, height, &err);
  if (err.code != 0) {
    napi_throw_error(env, NULL, err.message);
    weaveffi_error_clear(&err);
    return NULL;
  }
  napi_value ret;
  napi_create_int64(env, (int64_t)(intptr_t)result, &ret);
  return ret;
}

static napi_value Napi_weaveffi_image_crop(napi_env env, napi_callback_info info) {
  size_t argc = 4;
  napi_value args[4];
  napi_get_cb_info(env, info, &argc, args, NULL, NULL);
  uint32_t x;
  napi_get_value_uint32(env, args[0], &x);
  uint32_t y;
  napi_get_value_uint32(env, args[1], &y);
  uint32_t width;
  napi_get_value_uint32(env, args[2], &width);
  uint32_t height;
  napi_get_value_uint32(env, args[3], &height);
  weaveffi_error err = {0};
  weaveffi_image_Operation* result = weaveffi_image_crop(x, y, width, height, &err);
  if (err.code != 0) {
    napi_throw_error(env, NULL, err.message);
    weaveffi_error_clear(&err);
    return NULL;
  }
  napi_value ret;
  napi_create_int64(env, (int64_t)(intptr_t)result, &ret);
  return ret;
}

static napi_value Napi_weaveffi_image_rotate(napi_env env, napi_callback_info info) {
  size_t argc = 1;
  napi_value args[1];
  napi_get_cb_info(env, info, &argc, args, NULL, NULL);
  double degrees;
  napi_get_value_double(env, args[0], &degrees);
  weaveffi_error err = {0};
  weaveffi_image_Operation* result = weaveffi_image_rotate(degrees, &err);
  if (err.code != 0) {
    napi_throw_error(env, NULL, err.message);
    weaveffi_error_clear(&err);
    return NULL;
  }
  napi_value ret;
  napi_create_int64(env, (int64_t)(intptr_t)result, &ret);
  return ret;
}

static napi_value Napi_weaveffi_image_blur(napi_env env, napi_callback_info info) {
  size_t argc = 1;
  napi_value args[1];
  napi_get_cb_info(env, info, &argc, args, NULL, NULL);
  double sigma;
  napi_get_value_double(env, args[0], &sigma);
  weaveffi_error err = {0};
  weaveffi_image_Operation* result = weaveffi_image_blur(sigma, &err);
  if (err.code != 0) {
    napi_throw_error(env, NULL, err.message);
    weaveffi_error_clear(&err);
    return NULL;
  }
  napi_value ret;
  napi_create_int64(env, (int64_t)(intptr_t)result, &ret);
  return ret;
}

static napi_value Napi_weaveffi_image_grayscale(napi_env env, napi_callback_info info) {
  size_t argc = 0;
  napi_get_cb_info(env, info, &argc, NULL, NULL, NULL);
  weaveffi_error err = {0};
  weaveffi_image_Operation* result = weaveffi_image_grayscale(&err);
  if (err.code != 0) {
    napi_throw_error(env, NULL, err.message);
    weaveffi_error_clear(&err);
    return NULL;
  }
  napi_value ret;
  napi_create_int64(env, (int64_t)(intptr_t)result, &ret);
  return ret;
}

static napi_value Napi_weaveffi_image_process(napi_env env, napi_callback_info info) {
  size_t argc = 3;
  napi_value args[3];
  napi_get_cb_info(env, info, &argc, args, NULL, NULL);
  void* input_raw;
  size_t input_len;
  napi_get_buffer_info(env, args[0], &input_raw, &input_len);
  uint32_t ops_count;
  napi_get_array_length(env, args[1], &ops_count);
  weaveffi_image_Operation** ops_arr = (weaveffi_image_Operation**)malloc(sizeof(weaveffi_image_Operation*) * (ops_count + 1));
  for (uint32_t ops_i = 0; ops_i < ops_count; ops_i++) {
    napi_value ops_el;
    napi_get_element(env, args[1], ops_i, &ops_el);
    int64_t ops_sp;
    napi_get_value_int64(env, ops_el, &ops_sp);
    ops_arr[ops_i] = (weaveffi_image_Operation*)(intptr_t)ops_sp;
  }
  int32_t out_format;
  napi_get_value_int32(env, args[2], &out_format);
  weaveffi_error err = {0};
  size_t out_len;
  const uint8_t* result = weaveffi_image_process((const uint8_t*)input_raw, input_len, ops_arr, (size_t)ops_count, (weaveffi_image_ImageFormat)out_format, &out_len, &err);
  free(ops_arr);
  if (err.code != 0) {
    napi_throw_error(env, NULL, err.message);
    weaveffi_error_clear(&err);
    return NULL;
  }
  napi_value ret;
  napi_create_buffer_copy(env, out_len, result, NULL, &ret);
  weaveffi_free_bytes((uint8_t*)result, out_len);
  return ret;
}

static napi_value Napi_weaveffi_image_probe(napi_env env, napi_callback_info info) {
  size_t argc = 1;
  napi_value args[1];
  napi_get_cb_info(env, info, &argc, args, NULL, NULL);
  void* input_raw;
  size_t input_len;
  napi_get_buffer_info(env, args[0], &input_raw, &input_len);
  weaveffi_error err = {0};
  weaveffi_image_ImageInfo* result = weaveffi_image_probe((const uint8_t*)input_raw, input_len, &err);
  if (err.code != 0) {
    napi_throw_error(env, NULL, err.message);
    weaveffi_error_clear(&err);
    return NULL;
  }
  napi_value ret;
  napi_create_int64(env, (int64_t)(intptr_t)result, &ret);
  return ret;
}

static napi_value Init(napi_env env, napi_value exports) {
  napi_property_descriptor props[] = {
    { "resize", NULL, Napi_weaveffi_image_resize, NULL, NULL, NULL, napi_default, NULL },
    { "crop", NULL, Napi_weaveffi_image_crop, NULL, NULL, NULL, napi_default, NULL },
    { "rotate", NULL, Napi_weaveffi_image_rotate, NULL, NULL, NULL, napi_default, NULL },
    { "blur", NULL, Napi_weaveffi_image_blur, NULL, NULL, NULL, napi_default, NULL },
    { "grayscale", NULL, Napi_weaveffi_image_grayscale, NULL, NULL, NULL, napi_default, NULL },
    { "process", NULL, Napi_weaveffi_image_process, NULL, NULL, NULL, napi_default, NULL },
    { "probe", NULL, Napi_weaveffi_image_probe, NULL, NULL, NULL, napi_default, NULL },
  };
  napi_define_properties(env, exports, 7, props);
  return exports;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)

// END weaveffi_addon.c
