// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

import CWeaveFFI
import Foundation

public enum WeaveFFIError: Error, LocalizedError {
    case error(code: Int32, message: String)
    public var errorDescription: String? {
        switch self {
        case let .error(_, message): return message
        }
    }
    public var errorCode: Int32 {
        switch self {
        case let .error(code, _): return code
        }
    }
}

@inline(__always)
func check(_ err: inout weaveffi_error) throws {
    if err.code != 0 {
        let code = err.code
        let message = err.message.flatMap { String(cString: $0) } ?? ""
        weaveffi_error_clear(&err)
        throw WeaveFFIError.error(code: code, message: message)
    }
}

@inline(__always)
func withOptionalPointer<T, R>(to value: T?, _ body: (UnsafePointer<T>?) throws -> R) rethrows -> R {
    guard let value = value else { return try body(nil) }
    return try withUnsafePointer(to: value) { try body($0) }
}

/// Encoded image container.
public enum ImageFormat: Int32 {
    case png = 0
    case jpeg = 1
    case webp = 2
    case gif = 3
}

/// Operation discriminator. See Operation for which fields each kind requires.
public enum OpKind: Int32 {
    case resize = 0
    case crop = 1
    case rotate = 2
    case blur = 3
    case grayscale = 4
}

/// Single image operation. Build with the resize/crop/rotate/blur/grayscale
/// factory functions; pass a list to process(). Fields used per kind:
///   Resize    : width, height
///   Crop      : x, y, width, height
///   Rotate    : degrees (clockwise, in degrees)
///   Blur      : sigma   (Gaussian sigma, in pixels)
///   Grayscale : (none)
/// Unused fields are null.
public class Operation {
    let ptr: OpaquePointer

    init(ptr: OpaquePointer) {
        self.ptr = ptr
    }

    deinit {
        weaveffi_image_Operation_destroy(ptr)
    }

    public var kind: OpKind {
        return weaveffi_image_Operation_get_kind(ptr)
    }

    public var width: UInt32? {
        let p = weaveffi_image_Operation_get_width(ptr)
        return p?.pointee
    }

    public var height: UInt32? {
        let p = weaveffi_image_Operation_get_height(ptr)
        return p?.pointee
    }

    public var x: UInt32? {
        let p = weaveffi_image_Operation_get_x(ptr)
        return p?.pointee
    }

    public var y: UInt32? {
        let p = weaveffi_image_Operation_get_y(ptr)
        return p?.pointee
    }

    public var degrees: Double? {
        let p = weaveffi_image_Operation_get_degrees(ptr)
        return p?.pointee
    }

    public var sigma: Double? {
        let p = weaveffi_image_Operation_get_sigma(ptr)
        return p?.pointee
    }
}

/// Decoded image header information.
public class ImageInfo {
    let ptr: OpaquePointer

    init(ptr: OpaquePointer) {
        self.ptr = ptr
    }

    deinit {
        weaveffi_image_ImageInfo_destroy(ptr)
    }

    public var width: UInt32 {
        return weaveffi_image_ImageInfo_get_width(ptr)
    }

    public var height: UInt32 {
        return weaveffi_image_ImageInfo_get_height(ptr)
    }

    public var format: ImageFormat {
        return weaveffi_image_ImageInfo_get_format(ptr)
    }
}

public enum Image {
    /// Build a Resize operation.
    public static func resize(_ width: UInt32, _ height: UInt32) throws -> Operation {
        var err = weaveffi_error(code: 0, message: nil)
        let rv = weaveffi_image_resize(width, height, &err)
        try check(&err)
        guard let rv = rv else { throw WeaveFFIError.error(code: -1, message: "null pointer") }
        return Operation(ptr: rv)
    }
    /// Build a Crop operation (x,y is the top-left corner).
    public static func crop(_ x: UInt32, _ y: UInt32, _ width: UInt32, _ height: UInt32) throws -> Operation {
        var err = weaveffi_error(code: 0, message: nil)
        let rv = weaveffi_image_crop(x, y, width, height, &err)
        try check(&err)
        guard let rv = rv else { throw WeaveFFIError.error(code: -1, message: "null pointer") }
        return Operation(ptr: rv)
    }
    /// Build a Rotate operation (degrees clockwise).
    public static func rotate(_ degrees: Double) throws -> Operation {
        var err = weaveffi_error(code: 0, message: nil)
        let rv = weaveffi_image_rotate(degrees, &err)
        try check(&err)
        guard let rv = rv else { throw WeaveFFIError.error(code: -1, message: "null pointer") }
        return Operation(ptr: rv)
    }
    /// Build a Gaussian Blur operation (sigma in pixels).
    public static func blur(_ sigma: Double) throws -> Operation {
        var err = weaveffi_error(code: 0, message: nil)
        let rv = weaveffi_image_blur(sigma, &err)
        try check(&err)
        guard let rv = rv else { throw WeaveFFIError.error(code: -1, message: "null pointer") }
        return Operation(ptr: rv)
    }
    /// Build a Grayscale operation.
    public static func grayscale() throws -> Operation {
        var err = weaveffi_error(code: 0, message: nil)
        let rv = weaveffi_image_grayscale(&err)
        try check(&err)
        guard let rv = rv else { throw WeaveFFIError.error(code: -1, message: "null pointer") }
        return Operation(ptr: rv)
    }
    /// Apply ops in order, encode in out_format, return bytes.
    public static func process(_ input: Data, _ ops: [Operation], _ out_format: ImageFormat) throws -> Data {
        var err = weaveffi_error(code: 0, message: nil)
        let input_bytes = Array(input)
        let ops_ptrs = ops.map { $0.ptr }
        let result: Data = input_bytes.withUnsafeBufferPointer { input_buf in
            let input_ptr = input_buf.baseAddress!
            let input_len = input_buf.count
            ops_ptrs.withUnsafeBufferPointer { ops_buf in
                let ops_ptr = ops_buf.baseAddress
                let ops_len = ops_buf.count
                    return weaveffi_image_process(input_ptr, input_len, ops_ptr, ops_len, weaveffi_image_ImageFormat(out_format.rawValue), &err)
            }
        }
        try check(&err)
        return result
    }
    /// Decode the header only and return dimensions plus detected format.
    public static func probe(_ input: Data) throws -> ImageInfo {
        var err = weaveffi_error(code: 0, message: nil)
        let input_bytes = Array(input)
        let result: OpaquePointer? = input_bytes.withUnsafeBufferPointer { input_buf in
            let input_ptr = input_buf.baseAddress!
            let input_len = input_buf.count
                return weaveffi_image_probe(input_ptr, input_len, &err)
        }
        try check(&err)
        guard let result = result else { throw WeaveFFIError.error(code: -1, message: "null pointer") }
        return ImageInfo(ptr: result)
    }
}

// END WeaveImage.swift
