# Generated by WeaveFFI 0.4.0 from image.yml
# DO NOT EDIT — your changes will be overwritten.
# To regenerate: weaveffi generate image.yml -o <out>

from setuptools import setup

setup(
    name="weaveffi",
    version="0.1.0",
    packages=["weaveffi"],
)

# END setup.py
