# Generated by WeaveFFI 0.4.0 from image.yml
# DO NOT EDIT — your changes will be overwritten.
# To regenerate: weaveffi generate image.yml -o <out>

Gem::Specification.new do |s|
  s.name        = 'weave-image'
  s.version     = '0.1.0'
  s.summary     = 'Ruby FFI bindings for weave-image (auto-generated)'
  s.files       = Dir['lib/**/*.rb']
  s.require_paths = ['lib']

  s.add_dependency 'ffi', '~> 1.15'
end

# END weaveffi.gemspec
