# Generated by WeaveFFI 0.4.0 from image.yml
# DO NOT EDIT — your changes will be overwritten.
# To regenerate: weaveffi generate image.yml -o <out>

from enum import IntEnum
from typing import Dict, Iterator, List, Optional

# Encoded image container.
class ImageFormat(IntEnum):
    Png: int
    Jpeg: int
    Webp: int
    Gif: int

# Operation discriminator. See Operation for which fields each kind requires.
class OpKind(IntEnum):
    Resize: int
    Crop: int
    Rotate: int
    Blur: int
    Grayscale: int

# Single image operation. Build with the resize/crop/rotate/blur/grayscale
# factory functions; pass a list to process(). Fields used per kind:
#   Resize    : width, height
#   Crop      : x, y, width, height
#   Rotate    : degrees (clockwise, in degrees)
#   Blur      : sigma   (Gaussian sigma, in pixels)
#   Grayscale : (none)
# Unused fields are null.
class Operation:
    @property
    def kind(self) -> "OpKind": ...
    @property
    def width(self) -> Optional[int]: ...
    @property
    def height(self) -> Optional[int]: ...
    @property
    def x(self) -> Optional[int]: ...
    @property
    def y(self) -> Optional[int]: ...
    @property
    def degrees(self) -> Optional[float]: ...
    @property
    def sigma(self) -> Optional[float]: ...

# Decoded image header information.
class ImageInfo:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def format(self) -> "ImageFormat": ...

# Build a Resize operation.
def resize(width: int, height: int) -> "Operation": ...

# Build a Crop operation (x,y is the top-left corner).
def crop(x: int, y: int, width: int, height: int) -> "Operation": ...

# Build a Rotate operation (degrees clockwise).
def rotate(degrees: float) -> "Operation": ...

# Build a Gaussian Blur operation (sigma in pixels).
def blur(sigma: float) -> "Operation": ...

# Build a Grayscale operation.
def grayscale() -> "Operation": ...

# Apply ops in order, encode in out_format, return bytes.
def process(input: bytes, ops: List["Operation"], out_format: "ImageFormat") -> bytes: ...

# Decode the header only and return dimensions plus detected format.
def probe(input: bytes) -> "ImageInfo": ...

# END weaveffi.pyi
