// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

package com.weaveffi

class WeaveFFI {
    companion object {
        init { System.loadLibrary("weaveffi") }

        /**
         * Build a Resize operation.
         */
        @JvmStatic external fun resize(width: Long, height: Long): Long
        /**
         * Build a Crop operation (x,y is the top-left corner).
         */
        @JvmStatic external fun crop(x: Long, y: Long, width: Long, height: Long): Long
        /**
         * Build a Rotate operation (degrees clockwise).
         */
        @JvmStatic external fun rotate(degrees: Double): Long
        /**
         * Build a Gaussian Blur operation (sigma in pixels).
         */
        @JvmStatic external fun blur(sigma: Double): Long
        /**
         * Build a Grayscale operation.
         */
        @JvmStatic external fun grayscale(): Long
        /**
         * Apply ops in order, encode in out_format, return bytes.
         */
        @JvmStatic private external fun processJni(input: ByteArray, ops: LongArray, out_format: Int): ByteArray
        @JvmStatic fun process(input: ByteArray, ops: LongArray, out_format: ImageFormat): ByteArray = processJni(input, ops, out_format.value)
        /**
         * Decode the header only and return dimensions plus detected format.
         */
        @JvmStatic external fun probe(input: ByteArray): Long
    }
}

/** Encoded image container. */
enum class ImageFormat(val value: Int) {
    Png(0),
    Jpeg(1),
    Webp(2),
    Gif(3);

    companion object {
        fun fromValue(value: Int): ImageFormat = entries.first { it.value == value }
    }
}

/** Operation discriminator. See Operation for which fields each kind requires. */
enum class OpKind(val value: Int) {
    Resize(0),
    Crop(1),
    Rotate(2),
    Blur(3),
    Grayscale(4);

    companion object {
        fun fromValue(value: Int): OpKind = entries.first { it.value == value }
    }
}

/**
 * Single image operation. Build with the resize/crop/rotate/blur/grayscale
 * factory functions; pass a list to process(). Fields used per kind:
 *   Resize    : width, height
 *   Crop      : x, y, width, height
 *   Rotate    : degrees (clockwise, in degrees)
 *   Blur      : sigma   (Gaussian sigma, in pixels)
 *   Grayscale : (none)
 * Unused fields are null.
 */
class Operation internal constructor(private var handle: Long) : java.io.Closeable {
    companion object {
        init { System.loadLibrary("weaveffi") }

        @JvmStatic external fun nativeCreate(kind: Int, width: Long?, height: Long?, x: Long?, y: Long?, degrees: Double?, sigma: Double?): Long
        @JvmStatic external fun nativeDestroy(handle: Long)
        @JvmStatic external fun nativeGetKind(handle: Long): Int
        @JvmStatic external fun nativeGetWidth(handle: Long): Long?
        @JvmStatic external fun nativeGetHeight(handle: Long): Long?
        @JvmStatic external fun nativeGetX(handle: Long): Long?
        @JvmStatic external fun nativeGetY(handle: Long): Long?
        @JvmStatic external fun nativeGetDegrees(handle: Long): Double?
        @JvmStatic external fun nativeGetSigma(handle: Long): Double?

        fun create(kind: Int, width: Long?, height: Long?, x: Long?, y: Long?, degrees: Double?, sigma: Double?): Operation = Operation(nativeCreate(kind, width, height, x, y, degrees, sigma))
    }

    val kind: OpKind get() = nativeGetKind(handle)
    val width: Long? get() = nativeGetWidth(handle)
    val height: Long? get() = nativeGetHeight(handle)
    val x: Long? get() = nativeGetX(handle)
    val y: Long? get() = nativeGetY(handle)
    val degrees: Double? get() = nativeGetDegrees(handle)
    val sigma: Double? get() = nativeGetSigma(handle)

    override fun close() {
        if (handle != 0L) {
            nativeDestroy(handle)
            handle = 0L
        }
    }

    protected fun finalize() {
        close()
    }
}

/** Decoded image header information. */
class ImageInfo internal constructor(private var handle: Long) : java.io.Closeable {
    companion object {
        init { System.loadLibrary("weaveffi") }

        @JvmStatic external fun nativeCreate(width: Long, height: Long, format: Int): Long
        @JvmStatic external fun nativeDestroy(handle: Long)
        @JvmStatic external fun nativeGetWidth(handle: Long): Long
        @JvmStatic external fun nativeGetHeight(handle: Long): Long
        @JvmStatic external fun nativeGetFormat(handle: Long): Int

        fun create(width: Long, height: Long, format: Int): ImageInfo = ImageInfo(nativeCreate(width, height, format))
    }

    val width: Long get() = nativeGetWidth(handle)
    val height: Long get() = nativeGetHeight(handle)
    val format: ImageFormat get() = nativeGetFormat(handle)

    override fun close() {
        if (handle != 0L) {
            nativeDestroy(handle)
            handle = 0L
        }
    }

    protected fun finalize() {
        close()
    }
}

open class WeaveFFIException(val code: Int, message: String) : Exception(message)

// END WeaveFFI.kt
