// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

// swift-tools-version:5.7
import PackageDescription

let package = Package(
    name: "WeaveImage",
    products: [
        .library(name: "WeaveImage", targets: ["WeaveImage"]),
    ],
    targets: [
        .systemLibrary(name: "CWeaveImage"),
        .target(name: "WeaveImage", dependencies: ["CWeaveImage"]),
    ]
)

// END Package.swift
