// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

#include "weaveffi.h"

// Optional convenience wrappers can be added here in future versions.

// END weaveffi.c
