// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

#include <jni.h>
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include "weaveffi.h"

static void throw_weaveffi_error(JNIEnv* env, weaveffi_error* err) {
    const char* msg = err->message ? err->message : "WeaveFFI error";
    jclass exClass = (*env)->FindClass(env, "java/lang/RuntimeException");
    (*env)->ThrowNew(env, exClass, msg);
    weaveffi_error_clear(err);
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_WeaveFFI_resize(JNIEnv* env, jclass clazz, jlong width, jlong height) {
    weaveffi_error err = {0, NULL};
    weaveffi_image_Operation* rv = weaveffi_image_resize((uint32_t)width, (uint32_t)height, &err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return 0;
    }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_WeaveFFI_crop(JNIEnv* env, jclass clazz, jlong x, jlong y, jlong width, jlong height) {
    weaveffi_error err = {0, NULL};
    weaveffi_image_Operation* rv = weaveffi_image_crop((uint32_t)x, (uint32_t)y, (uint32_t)width, (uint32_t)height, &err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return 0;
    }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_WeaveFFI_rotate(JNIEnv* env, jclass clazz, jdouble degrees) {
    weaveffi_error err = {0, NULL};
    weaveffi_image_Operation* rv = weaveffi_image_rotate((double)degrees, &err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return 0;
    }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_WeaveFFI_blur(JNIEnv* env, jclass clazz, jdouble sigma) {
    weaveffi_error err = {0, NULL};
    weaveffi_image_Operation* rv = weaveffi_image_blur((double)sigma, &err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return 0;
    }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_WeaveFFI_grayscale(JNIEnv* env, jclass clazz) {
    weaveffi_error err = {0, NULL};
    weaveffi_image_Operation* rv = weaveffi_image_grayscale(&err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return 0;
    }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jbyteArray JNICALL Java_com_weaveffi_WeaveFFI_processJni(JNIEnv* env, jclass clazz, jbyteArray input, jlongArray ops, jint out_format) {
    weaveffi_error err = {0, NULL};
    jboolean input_is_copy = 0;
    jbyte* input_elems = (*env)->GetByteArrayElements(env, input, &input_is_copy);
    jsize input_len = (*env)->GetArrayLength(env, input);
    jlong* ops_elems = (*env)->GetLongArrayElements(env, ops, NULL);
    jsize ops_len = (*env)->GetArrayLength(env, ops);
    size_t out_len = 0;
    const uint8_t* rv = weaveffi_image_process((const uint8_t*)input_elems, (size_t)input_len, (const void*)ops_elems, (size_t)ops_len, (int32_t)out_format, &out_len, &err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return NULL;
    }
    jbyteArray out = (*env)->NewByteArray(env, (jsize)out_len);
    if (out && rv) { (*env)->SetByteArrayRegion(env, out, 0, (jsize)out_len, (const jbyte*)rv); }
    weaveffi_free_bytes((uint8_t*)rv, (size_t)out_len);
    (*env)->ReleaseByteArrayElements(env, input, input_elems, 0);
    (*env)->ReleaseLongArrayElements(env, ops, ops_elems, 0);
    return out;
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_WeaveFFI_probe(JNIEnv* env, jclass clazz, jbyteArray input) {
    weaveffi_error err = {0, NULL};
    jboolean input_is_copy = 0;
    jbyte* input_elems = (*env)->GetByteArrayElements(env, input, &input_is_copy);
    jsize input_len = (*env)->GetArrayLength(env, input);
    weaveffi_image_ImageInfo* rv = weaveffi_image_probe((const uint8_t*)input_elems, (size_t)input_len, &err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return 0;
    }
    (*env)->ReleaseByteArrayElements(env, input, input_elems, 0);
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_Operation_nativeCreate(JNIEnv* env, jclass clazz, jint kind, jobject width, jobject height, jobject x, jobject y, jobject degrees, jobject sigma) {
    weaveffi_error err = {0, NULL};
    int64_t width_val = 0;
    const int64_t* width_ptr = NULL;
    if (width != NULL) {
        jclass width_cls = (*env)->FindClass(env, "java/lang/Long");
        jmethodID width_mid = (*env)->GetMethodID(env, width_cls, "longValue", "()J");
        width_val = (int64_t)(*env)->CallLongMethod(env, width, width_mid);
        width_ptr = &width_val;
    }
    int64_t height_val = 0;
    const int64_t* height_ptr = NULL;
    if (height != NULL) {
        jclass height_cls = (*env)->FindClass(env, "java/lang/Long");
        jmethodID height_mid = (*env)->GetMethodID(env, height_cls, "longValue", "()J");
        height_val = (int64_t)(*env)->CallLongMethod(env, height, height_mid);
        height_ptr = &height_val;
    }
    int64_t x_val = 0;
    const int64_t* x_ptr = NULL;
    if (x != NULL) {
        jclass x_cls = (*env)->FindClass(env, "java/lang/Long");
        jmethodID x_mid = (*env)->GetMethodID(env, x_cls, "longValue", "()J");
        x_val = (int64_t)(*env)->CallLongMethod(env, x, x_mid);
        x_ptr = &x_val;
    }
    int64_t y_val = 0;
    const int64_t* y_ptr = NULL;
    if (y != NULL) {
        jclass y_cls = (*env)->FindClass(env, "java/lang/Long");
        jmethodID y_mid = (*env)->GetMethodID(env, y_cls, "longValue", "()J");
        y_val = (int64_t)(*env)->CallLongMethod(env, y, y_mid);
        y_ptr = &y_val;
    }
    double degrees_val = 0.0;
    const double* degrees_ptr = NULL;
    if (degrees != NULL) {
        jclass degrees_cls = (*env)->FindClass(env, "java/lang/Double");
        jmethodID degrees_mid = (*env)->GetMethodID(env, degrees_cls, "doubleValue", "()D");
        degrees_val = (*env)->CallDoubleMethod(env, degrees, degrees_mid);
        degrees_ptr = &degrees_val;
    }
    double sigma_val = 0.0;
    const double* sigma_ptr = NULL;
    if (sigma != NULL) {
        jclass sigma_cls = (*env)->FindClass(env, "java/lang/Double");
        jmethodID sigma_mid = (*env)->GetMethodID(env, sigma_cls, "doubleValue", "()D");
        sigma_val = (*env)->CallDoubleMethod(env, sigma, sigma_mid);
        sigma_ptr = &sigma_val;
    }
    weaveffi_image_Operation* rv = weaveffi_image_Operation_create((int32_t)kind, width_ptr, height_ptr, x_ptr, y_ptr, degrees_ptr, sigma_ptr, &err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return 0;
    }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT void JNICALL Java_com_weaveffi_Operation_nativeDestroy(JNIEnv* env, jclass clazz, jlong handle) {
    weaveffi_image_Operation_destroy((weaveffi_image_Operation*)(intptr_t)handle);
}

JNIEXPORT jint JNICALL Java_com_weaveffi_Operation_nativeGetKind(JNIEnv* env, jclass clazz, jlong handle) {
    int32_t rv = weaveffi_image_Operation_get_kind((const weaveffi_image_Operation*)(intptr_t)handle);
    return (jint)rv;
}

JNIEXPORT jobject JNICALL Java_com_weaveffi_Operation_nativeGetWidth(JNIEnv* env, jclass clazz, jlong handle) {
    const void* rv = weaveffi_image_Operation_get_width((const weaveffi_image_Operation*)(intptr_t)handle);
    if (!rv) { return 0; }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jobject JNICALL Java_com_weaveffi_Operation_nativeGetHeight(JNIEnv* env, jclass clazz, jlong handle) {
    const void* rv = weaveffi_image_Operation_get_height((const weaveffi_image_Operation*)(intptr_t)handle);
    if (!rv) { return 0; }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jobject JNICALL Java_com_weaveffi_Operation_nativeGetX(JNIEnv* env, jclass clazz, jlong handle) {
    const void* rv = weaveffi_image_Operation_get_x((const weaveffi_image_Operation*)(intptr_t)handle);
    if (!rv) { return 0; }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jobject JNICALL Java_com_weaveffi_Operation_nativeGetY(JNIEnv* env, jclass clazz, jlong handle) {
    const void* rv = weaveffi_image_Operation_get_y((const weaveffi_image_Operation*)(intptr_t)handle);
    if (!rv) { return 0; }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jobject JNICALL Java_com_weaveffi_Operation_nativeGetDegrees(JNIEnv* env, jclass clazz, jlong handle) {
    const void* rv = weaveffi_image_Operation_get_degrees((const weaveffi_image_Operation*)(intptr_t)handle);
    if (!rv) { return 0; }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jobject JNICALL Java_com_weaveffi_Operation_nativeGetSigma(JNIEnv* env, jclass clazz, jlong handle) {
    const void* rv = weaveffi_image_Operation_get_sigma((const weaveffi_image_Operation*)(intptr_t)handle);
    if (!rv) { return 0; }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_ImageInfo_nativeCreate(JNIEnv* env, jclass clazz, jlong width, jlong height, jint format) {
    weaveffi_error err = {0, NULL};
    weaveffi_image_ImageInfo* rv = weaveffi_image_ImageInfo_create((uint32_t)width, (uint32_t)height, (int32_t)format, &err);
    if (err.code != 0) {
        throw_weaveffi_error(env, &err);
        return 0;
    }
    return (jlong)(intptr_t)rv;
}

JNIEXPORT void JNICALL Java_com_weaveffi_ImageInfo_nativeDestroy(JNIEnv* env, jclass clazz, jlong handle) {
    weaveffi_image_ImageInfo_destroy((weaveffi_image_ImageInfo*)(intptr_t)handle);
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_ImageInfo_nativeGetWidth(JNIEnv* env, jclass clazz, jlong handle) {
    uint32_t rv = weaveffi_image_ImageInfo_get_width((const weaveffi_image_ImageInfo*)(intptr_t)handle);
    return (jlong)rv;
}

JNIEXPORT jlong JNICALL Java_com_weaveffi_ImageInfo_nativeGetHeight(JNIEnv* env, jclass clazz, jlong handle) {
    uint32_t rv = weaveffi_image_ImageInfo_get_height((const weaveffi_image_ImageInfo*)(intptr_t)handle);
    return (jlong)rv;
}

JNIEXPORT jint JNICALL Java_com_weaveffi_ImageInfo_nativeGetFormat(JNIEnv* env, jclass clazz, jlong handle) {
    int32_t rv = weaveffi_image_ImageInfo_get_format((const weaveffi_image_ImageInfo*)(intptr_t)handle);
    return (jint)rv;
}


// END weaveffi_jni.c
