// Generated by WeaveFFI 0.4.0 from image.yml
// DO NOT EDIT — your changes will be overwritten.
// To regenerate: weaveffi generate image.yml -o <out>

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <unordered_map>
#include <memory>
#include <stdexcept>

extern "C" {

typedef uint64_t weaveffi_handle_t;

typedef struct weaveffi_error {
    int32_t code;
    const char* message;
} weaveffi_error;

void weaveffi_error_clear(weaveffi_error* err);
void weaveffi_free_string(const char* ptr);
void weaveffi_free_bytes(uint8_t* ptr, size_t len);

typedef struct weaveffi_cancel_token weaveffi_cancel_token;
weaveffi_cancel_token* weaveffi_cancel_token_create(void);
void weaveffi_cancel_token_cancel(weaveffi_cancel_token* token);
bool weaveffi_cancel_token_is_cancelled(const weaveffi_cancel_token* token);
void weaveffi_cancel_token_destroy(weaveffi_cancel_token* token);

/** Encoded image container. */
typedef enum { weaveffi_image_ImageFormat_Png = 0, weaveffi_image_ImageFormat_Jpeg = 1, weaveffi_image_ImageFormat_Webp = 2, weaveffi_image_ImageFormat_Gif = 3 } weaveffi_image_ImageFormat;
/** Operation discriminator. See Operation for which fields each kind requires. */
typedef enum { weaveffi_image_OpKind_Resize = 0, weaveffi_image_OpKind_Crop = 1, weaveffi_image_OpKind_Rotate = 2, weaveffi_image_OpKind_Blur = 3, weaveffi_image_OpKind_Grayscale = 4 } weaveffi_image_OpKind;
/**
 * Single image operation. Build with the resize/crop/rotate/blur/grayscale
 * factory functions; pass a list to process(). Fields used per kind:
 *   Resize    : width, height
 *   Crop      : x, y, width, height
 *   Rotate    : degrees (clockwise, in degrees)
 *   Blur      : sigma   (Gaussian sigma, in pixels)
 *   Grayscale : (none)
 * Unused fields are null.
 */
typedef struct weaveffi_image_Operation weaveffi_image_Operation;
weaveffi_image_Operation* weaveffi_image_Operation_create(weaveffi_image_OpKind kind, const uint32_t* width, const uint32_t* height, const uint32_t* x, const uint32_t* y, const double* degrees, const double* sigma, weaveffi_error* out_err);
void weaveffi_image_Operation_destroy(weaveffi_image_Operation* ptr);
weaveffi_image_OpKind weaveffi_image_Operation_get_kind(const weaveffi_image_Operation* ptr);
uint32_t* weaveffi_image_Operation_get_width(const weaveffi_image_Operation* ptr);
uint32_t* weaveffi_image_Operation_get_height(const weaveffi_image_Operation* ptr);
uint32_t* weaveffi_image_Operation_get_x(const weaveffi_image_Operation* ptr);
uint32_t* weaveffi_image_Operation_get_y(const weaveffi_image_Operation* ptr);
double* weaveffi_image_Operation_get_degrees(const weaveffi_image_Operation* ptr);
double* weaveffi_image_Operation_get_sigma(const weaveffi_image_Operation* ptr);
/** Decoded image header information. */
typedef struct weaveffi_image_ImageInfo weaveffi_image_ImageInfo;
weaveffi_image_ImageInfo* weaveffi_image_ImageInfo_create(uint32_t width, uint32_t height, weaveffi_image_ImageFormat format, weaveffi_error* out_err);
void weaveffi_image_ImageInfo_destroy(weaveffi_image_ImageInfo* ptr);
uint32_t weaveffi_image_ImageInfo_get_width(const weaveffi_image_ImageInfo* ptr);
uint32_t weaveffi_image_ImageInfo_get_height(const weaveffi_image_ImageInfo* ptr);
weaveffi_image_ImageFormat weaveffi_image_ImageInfo_get_format(const weaveffi_image_ImageInfo* ptr);
/** Build a Resize operation. */
weaveffi_image_Operation* weaveffi_image_resize(uint32_t width, uint32_t height, weaveffi_error* out_err);
/** Build a Crop operation (x,y is the top-left corner). */
weaveffi_image_Operation* weaveffi_image_crop(uint32_t x, uint32_t y, uint32_t width, uint32_t height, weaveffi_error* out_err);
/** Build a Rotate operation (degrees clockwise). */
weaveffi_image_Operation* weaveffi_image_rotate(double degrees, weaveffi_error* out_err);
/** Build a Gaussian Blur operation (sigma in pixels). */
weaveffi_image_Operation* weaveffi_image_blur(double sigma, weaveffi_error* out_err);
/** Build a Grayscale operation. */
weaveffi_image_Operation* weaveffi_image_grayscale(weaveffi_error* out_err);
/** Apply ops in order, encode in out_format, return bytes. */
const uint8_t* weaveffi_image_process(const uint8_t* input_ptr, size_t input_len, weaveffi_image_Operation* const* ops, size_t ops_len, weaveffi_image_ImageFormat out_format, size_t* out_len, weaveffi_error* out_err);
/** Decode the header only and return dimensions plus detected format. */
weaveffi_image_ImageInfo* weaveffi_image_probe(const uint8_t* input_ptr, size_t input_len, weaveffi_error* out_err);

} // extern "C"

namespace weave_image {

class WeaveFFIError : public std::runtime_error {
    int32_t code_;

public:
    WeaveFFIError(int32_t code, const std::string& msg) : std::runtime_error(msg), code_(code) {}
    int32_t code() const { return code_; }
};

/** Encoded image container. */
enum class ImageFormat : int32_t {
    Png = 0,
    Jpeg = 1,
    Webp = 2,
    Gif = 3
};

/** Operation discriminator. See Operation for which fields each kind requires. */
enum class OpKind : int32_t {
    Resize = 0,
    Crop = 1,
    Rotate = 2,
    Blur = 3,
    Grayscale = 4
};

/**
 * Single image operation. Build with the resize/crop/rotate/blur/grayscale
 * factory functions; pass a list to process(). Fields used per kind:
 *   Resize    : width, height
 *   Crop      : x, y, width, height
 *   Rotate    : degrees (clockwise, in degrees)
 *   Blur      : sigma   (Gaussian sigma, in pixels)
 *   Grayscale : (none)
 * Unused fields are null.
 */
class Operation {
    void* handle_;

public:
    explicit Operation(void* h) : handle_(h) {}

    ~Operation() {
        if (handle_) weaveffi_image_Operation_destroy(static_cast<weaveffi_image_Operation*>(handle_));
    }

    Operation(const Operation&) = delete;
    Operation& operator=(const Operation&) = delete;

    Operation(Operation&& other) noexcept : handle_(other.handle_) {
        other.handle_ = nullptr;
    }

    Operation& operator=(Operation&& other) noexcept {
        if (this != &other) {
            if (handle_) weaveffi_image_Operation_destroy(static_cast<weaveffi_image_Operation*>(handle_));
            handle_ = other.handle_;
            other.handle_ = nullptr;
        }
        return *this;
    }

    void* handle() const { return handle_; }

    OpKind kind() const {
        return static_cast<OpKind>(weaveffi_image_Operation_get_kind(static_cast<const weaveffi_image_Operation*>(handle_)));
    }

    std::optional<uint32_t> width() const {
        auto* raw = weaveffi_image_Operation_get_width(static_cast<const weaveffi_image_Operation*>(handle_));
        if (!raw) return std::nullopt;
        return *raw;
    }

    std::optional<uint32_t> height() const {
        auto* raw = weaveffi_image_Operation_get_height(static_cast<const weaveffi_image_Operation*>(handle_));
        if (!raw) return std::nullopt;
        return *raw;
    }

    std::optional<uint32_t> x() const {
        auto* raw = weaveffi_image_Operation_get_x(static_cast<const weaveffi_image_Operation*>(handle_));
        if (!raw) return std::nullopt;
        return *raw;
    }

    std::optional<uint32_t> y() const {
        auto* raw = weaveffi_image_Operation_get_y(static_cast<const weaveffi_image_Operation*>(handle_));
        if (!raw) return std::nullopt;
        return *raw;
    }

    std::optional<double> degrees() const {
        auto* raw = weaveffi_image_Operation_get_degrees(static_cast<const weaveffi_image_Operation*>(handle_));
        if (!raw) return std::nullopt;
        return *raw;
    }

    std::optional<double> sigma() const {
        auto* raw = weaveffi_image_Operation_get_sigma(static_cast<const weaveffi_image_Operation*>(handle_));
        if (!raw) return std::nullopt;
        return *raw;
    }

};

/** Decoded image header information. */
class ImageInfo {
    void* handle_;

public:
    explicit ImageInfo(void* h) : handle_(h) {}

    ~ImageInfo() {
        if (handle_) weaveffi_image_ImageInfo_destroy(static_cast<weaveffi_image_ImageInfo*>(handle_));
    }

    ImageInfo(const ImageInfo&) = delete;
    ImageInfo& operator=(const ImageInfo&) = delete;

    ImageInfo(ImageInfo&& other) noexcept : handle_(other.handle_) {
        other.handle_ = nullptr;
    }

    ImageInfo& operator=(ImageInfo&& other) noexcept {
        if (this != &other) {
            if (handle_) weaveffi_image_ImageInfo_destroy(static_cast<weaveffi_image_ImageInfo*>(handle_));
            handle_ = other.handle_;
            other.handle_ = nullptr;
        }
        return *this;
    }

    void* handle() const { return handle_; }

    uint32_t width() const {
        return weaveffi_image_ImageInfo_get_width(static_cast<const weaveffi_image_ImageInfo*>(handle_));
    }

    uint32_t height() const {
        return weaveffi_image_ImageInfo_get_height(static_cast<const weaveffi_image_ImageInfo*>(handle_));
    }

    ImageFormat format() const {
        return static_cast<ImageFormat>(weaveffi_image_ImageInfo_get_format(static_cast<const weaveffi_image_ImageInfo*>(handle_)));
    }

};

/** Build a Resize operation. */
inline Operation image_resize(uint32_t width, uint32_t height) {
    weaveffi_error err{};
    auto result = weaveffi_image_resize(width, height, &err);
    if (err.code != 0) {
        std::string msg(err.message ? err.message : "unknown error");
        int32_t code = err.code;
        weaveffi_error_clear(&err);
        throw WeaveFFIError(code, msg);
    }
    return Operation(result);
}

/** Build a Crop operation (x,y is the top-left corner). */
inline Operation image_crop(uint32_t x, uint32_t y, uint32_t width, uint32_t height) {
    weaveffi_error err{};
    auto result = weaveffi_image_crop(x, y, width, height, &err);
    if (err.code != 0) {
        std::string msg(err.message ? err.message : "unknown error");
        int32_t code = err.code;
        weaveffi_error_clear(&err);
        throw WeaveFFIError(code, msg);
    }
    return Operation(result);
}

/** Build a Rotate operation (degrees clockwise). */
inline Operation image_rotate(double degrees) {
    weaveffi_error err{};
    auto result = weaveffi_image_rotate(degrees, &err);
    if (err.code != 0) {
        std::string msg(err.message ? err.message : "unknown error");
        int32_t code = err.code;
        weaveffi_error_clear(&err);
        throw WeaveFFIError(code, msg);
    }
    return Operation(result);
}

/** Build a Gaussian Blur operation (sigma in pixels). */
inline Operation image_blur(double sigma) {
    weaveffi_error err{};
    auto result = weaveffi_image_blur(sigma, &err);
    if (err.code != 0) {
        std::string msg(err.message ? err.message : "unknown error");
        int32_t code = err.code;
        weaveffi_error_clear(&err);
        throw WeaveFFIError(code, msg);
    }
    return Operation(result);
}

/** Build a Grayscale operation. */
inline Operation image_grayscale() {
    weaveffi_error err{};
    auto result = weaveffi_image_grayscale(&err);
    if (err.code != 0) {
        std::string msg(err.message ? err.message : "unknown error");
        int32_t code = err.code;
        weaveffi_error_clear(&err);
        throw WeaveFFIError(code, msg);
    }
    return Operation(result);
}

/** Apply ops in order, encode in out_format, return bytes. */
inline std::vector<uint8_t> image_process(const std::vector<uint8_t>& input, const std::vector<Operation>& ops, ImageFormat out_format) {
    std::vector<const weaveffi_image_Operation*> ops_ptrs;
    ops_ptrs.reserve(ops.size());
    for (const auto& item : ops) ops_ptrs.push_back(static_cast<const weaveffi_image_Operation*>(item.handle()));
    size_t out_len = 0;
    weaveffi_error err{};
    auto result = weaveffi_image_process(input.data(), input.size(), ops_ptrs.data(), ops_ptrs.size(), static_cast<weaveffi_image_ImageFormat>(static_cast<int32_t>(out_format)), &out_len, &err);
    if (err.code != 0) {
        std::string msg(err.message ? err.message : "unknown error");
        int32_t code = err.code;
        weaveffi_error_clear(&err);
        throw WeaveFFIError(code, msg);
    }
    std::vector<uint8_t> ret(result, result + out_len);
    weaveffi_free_bytes(const_cast<uint8_t*>(result), out_len);
    return ret;
}

/** Decode the header only and return dimensions plus detected format. */
inline ImageInfo image_probe(const std::vector<uint8_t>& input) {
    weaveffi_error err{};
    auto result = weaveffi_image_probe(input.data(), input.size(), &err);
    if (err.code != 0) {
        std::string msg(err.message ? err.message : "unknown error");
        int32_t code = err.code;
        weaveffi_error_clear(&err);
        throw WeaveFFIError(code, msg);
    }
    return ImageInfo(result);
}

} // namespace weave_image

// END weaveffi.hpp
